apiVersion: v2
name: cf-loki
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: loki
    version: 6.49.0
    repository: https://grafana.github.io/helm-charts
    condition: cf-loki.enabled
