# this manifest has to be installed AFTER the base external-secrets chart is installed
# it will throw an error because the CRDs are not installed yet
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ic-certs-secret-sync
  namespace: external-secrets
spec:
  refreshInterval: 0h0m30s # rate SecretManager pulls
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store # name of the SecretStore (or kind specified)
  target:
    name: ic-ca-certs # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: ca.crt # name of the key within the secrets manager secret to parse
      remoteRef:
        key: ic-ca-certs
